name: Lint github action + Update doc
on:
  push:
    branches:
      - action

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    name: lint and test
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash
      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color
        shell: bash
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: pip install -r scripts/documentation/requirements.txt
        name: install dependencies
      - name: generate doc
        run: python ./scripts/documentation/main.py -p .github/workflows/ > ./doc.md
      - uses: remerge/confluence-markdown-sync@develop
        with:
          from: './doc.md'
          to: '2299723861'
          cloud: remerge
          user: ${{secrets.confluence_user_email}}
          token: ${{secrets.confluence_token}}
