---
name: Lint github action
on: [push]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    name: lint
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash
      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color
        shell: bash
