---
name: Update github actions doc
on:
  workflow_run:
    workflows: ["Lint github action"]
    types: [completed]
    branches:
      - main

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: generate reusable workflow docs in confluence
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - run: pip install -r scripts/documentation/requirements.txt
        name: install dependencies
      - name: generate doc
        run: python ./scripts/documentation/main.py -p .github/workflows/ > ./doc.md
      - uses: remerge/Github-action-confluence-sync@develop
        with:
          from: "./doc.md"
          to: "2306670708"
          cloud: remerge
          user: ${{secrets.confluence_user_email}}
          token: ${{secrets.confluence_token}}
