# we want to run the "go get $dependency && go mod tidy && open PR if needed"
# workflow for every dependency every time the main branch gets updated.
# this fixes possible merge conflicts in existing branches/PRs and closes them
# if they're not needed any more. the easiest way to trigger that code seems
# to be sending a bunch of events to "this" repo.

name: Check repos I depend on

on:
  workflow_call:
    inputs:
      dependencies:
        type: string
        required: true
        description: "String containing a JSON list (because we can't pass a list as an input)"
    secrets:
      ssh_key:
        description: "SSH key to use"
        required: true
      pat_for_updating:
        description: "Need a PAT with update permissions to send events to a repo"
        required: true

jobs:
  notify-self-about-all-dependencies:
    strategy:
      matrix:
        dependency: ${{ fromJSON(inputs.dependencies) }}
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ matrix.dependency }}
      shell: bash

    - name: Dispatch Event
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.pat_for_updating }}
        repository: ${{ github.repository }}
        event-type: new-main-commit
        client-payload: |
          {
            "repo_path": "github.com/remerge/${{ matrix.dependency }}",
            "repo_name": "remerge/${{ matrix.dependency }}"
          }
