# we want to run the "go get $dependency && go mod tidy && open PR if needed"
# workflow for every dependency every time the main branch gets updated.
# this fixes possible merge conflicts in existing branches/PRs and closes them
# if they're not needed any more.

name: Check repos I depend on

on:
  workflow_call:
    inputs:
      dependencies:
        type: string
        required: true
        description: "String containing a JSON list (because we can't pass a list as an input)"
    secrets:
      app_id:
        required: true
        description: "App id that we exchange for a token."
      app_key:
        description: "Private app key that we can exchange for a token."
        required: true
      ssh_key:
        description: "Need an SSH key to fetch private repos"
        required: true

jobs:
  notify-self-about-all-dependencies:
    strategy:
      matrix:
        dependency: ${{ fromJSON(inputs.dependencies) }}
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ matrix.dependency }}
      shell: bash

    - name: Check possible dependency update
      uses: remerge/check-possible-dependency-update@main
      with:
        repo_path: "github.com/remerge/${{ matrix.dependency }}"
        repo_name: "remerge/${{ matrix.dependency }}"
        app_id: ${{ secrets.app_id }}
        app_key: ${{ secrets.app_key }}
        ssh_key: ${{ secrets.ssh_key }}
