# Runs common checks for Go package: lint (fmt, modules, static, shadowing),
# tests and race.

name: Go checks

on:
  workflow_call:
    inputs:
      golang_version:
        type: string
        required: false
        default: ""
        description: "Override Golang version in go.mod"
      goprivate:
        type: string
        required: false
        default: "github.com/remerge"
        description: "Set GOPRIVATE"
      no-race:
        type: boolean
        required: false
        default: false
        description: "Run race detector"
      compose-file:
        type: string
        required: false
        default: docker-compose.yml
        description: "Docker-compose file to detect"
      compose-wait:
        type: number
        required: false
        default: 1
        description: "Seconds to wait after docker-compose initialised"
      no-compose:
        type: boolean
        required: false
        default: false
        description: "Do not run docker-compose even compose file is present"
    secrets:
      gh_auth_token:
        required: true
        description: "Github auth token i.e username:gh_token"

jobs:
  go-test:
    name: "Go lint and test"
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: ${{ inputs.goprivate }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - run: echo "GO_VERSION=$(grep '^go ' < go.mod | awk '{print $2}')" >> "$GITHUB_ENV"
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ inputs.golang_version || env.GO_VERSION }}
    - name: Update git config
      env:
        GH_AUTH_TOKEN: ${{ secrets.gh_auth_token }}
      run: |
        git config --global url."https://${GH_AUTH_TOKEN}@github.com/".insteadOf https://github.com/

    - run: make lint
    - run: 'docker-compose -f "${{ inputs.compose-file }}" up -d --build && sleep ${{ inputs.compose-wait }}'
      if: "${{ !inputs.no-compose && hashFiles(inputs.compose-file) != '' }}"
    - run: make test-nocache
    - run: 'docker-compose -f "${{ inputs.compose-file }}" down'
      if: "${{ always() && !inputs.no-compose && hashFiles(inputs.compose-file) != '' }}"



  go-race:
    name: 'Go test with race'
    if: '!inputs.no-race'
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: ${{ inputs.goprivate }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - run: echo "GO_VERSION=$(grep '^go ' < go.mod | awk '{print $2}')" >> "$GITHUB_ENV"
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ inputs.golang_version || env.GO_VERSION }}
    - name: Update git config
      env:
        GH_AUTH_TOKEN: ${{ secrets.gh_auth_token }}
      run: |
        git config --global url."https://${GH_AUTH_TOKEN}@github.com/".insteadOf https://github.com/

    - run: 'docker-compose -f "${{ inputs.compose-file }}" up -d --build && sleep ${{ inputs.compose-wait }}'
      if: "${{ !inputs.no-compose && hashFiles(inputs.compose-file) != '' }}"
    - run: make race-nocache
    - run: 'docker-compose -f "${{ inputs.compose-file }}" down'
      if: "${{ always() && !inputs.no-compose && hashFiles(inputs.compose-file) != '' }}"
