# Runs common checks for Go package: lint (fmt, modules, static, shadowing),
# tests and race.

name: Go checks

on:
  workflow_call:
    inputs:
      golang_version:
        type: string
        required: false
        default: "1.17"
      goprivate:
        type: string
        required: false
        default: "github.com/remerge"
    secrets:
      gh_auth_token:
        required: true

jobs:
  go-test:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: ${{ inputs.goprivate }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ inputs.golang_version }}
    - name: Update git config
      env:
        GH_AUTH_TOKEN: ${{ secrets.gh_auth_token }}
      run: |
        git config --global url."https://${GH_AUTH_TOKEN}@github.com/".insteadOf https://github.com/

    - run: make lint
    - run: make test-nocache
    - run: make race-nocache
