# Runs common checks for Go package: lint (fmt, modules, static, shadowing),
# tests and race.

name: Go checks

on:
  workflow_call:
    inputs:
      golang_version:
        type: string
        required: false
        default: ""
        description: "Override Golang version in go.mod"
      goprivate:
        type: string
        required: false
        default: "github.com/remerge"
        description: "Set GOPRIVATE"
      no-race:
        type: boolean
        required: false
        default: false
        description: "Run race detector"
      lint-target:
        type: string
        required: false
        default: 'lint'
        description: "Lint Make target"
    secrets:
      ssh_key:
        description: "SSH key to use"
        required: true

env:
  GOPRIVATE: ${{ inputs.goprivate }}

jobs:
  go-test:
    name: "lint_and_test"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: go modules cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg
        key: ${{ runner.os }}-go-mod-${{ github.job }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-mod-${{ github.job }}-
    - name: go tools cache
      uses: actions/cache@v3
      with:
        path: |
          ${{ github.workspace }}/mkf/.tools
        key: ${{ runner.os }}-go-tools-${{ github.job }}
        restore-keys: |
          ${{ runner.os }}-go-tools-${{ github.job }}
    - run: echo "GO_VERSION=$(grep '^go ' < go.mod | awk '{print $2}')" >> "$GITHUB_ENV"
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ inputs.golang_version || env.GO_VERSION }}

    - uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: '${{ secrets.ssh_key }}'
    - run: 'git config --global url."git@github.com:".insteadOf "https://github.com/"'

    - run: make ${{ inputs.lint-target }}
    - run: make test-nocache
    - run: make race-nocache
      if: '!inputs.no-race'
