name: Build go binary and build + push docker image

on:
  workflow_call:
    inputs:
      golang_version:
        description: "Override Go version in go.mod"
        type: string
        required: false
        default: ""
      goprivate:
        description: "Go private packages prefix"
        type: string
        required: false
        default: "github.com/remerge"
      registry:
        required: true
        type: string
        description: "Docker container registry"
      image_name:
        required: true
        type: string
        description: "Docker image to deploy"
    secrets:
      gh_auth_token:
        required: true
        description: "Github auth token i.e username:gh_token"
      gh_token:
        required: true
        description: "Github token"
jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: ${{ inputs.goprivate }}
    steps:
      - uses: actions/checkout@v2

      - run: echo "GO_VERSION=$(grep '^go ' < go.mod | awk '{print $2}')" >> "$GITHUB_ENV"
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ inputs.golang_version || env.GO_VERSION }}

      - name: Update git config
        env:
          GH_AUTH_TOKEN: ${{ secrets.gh_auth_token }}
        run: |
          git config --global url."https://${GH_AUTH_TOKEN}@github.com/".insteadOf https://github.com/

      - name: Build
        if: ${{ github.event_name != 'pull_request' }}
        run: make dist

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.gh_token }}

      - name: Extract metadata (tags, labels) for Docker
        if: ${{ github.event_name != 'pull_request' }}
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ inputs.registry }}/${{ inputs.image_name }}
          tags: |
            type=sha

      - name: Cache register
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile') }}

      - name: Build and push Docker image
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
