---
name: go-test

on:
  workflow_call:
    inputs:
      go-private:
        type: string
        required: false
        default: "github.com/remerge"
        description: "Set GOPRIVATE"
      no-race:
        type: boolean
        required: false
        default: false
        description: "Run race detector"
      compose-file:
        type: string
        required: false
        default: docker-compose.yml
        description: "Docker-compose file to detect"
      compose-wait:
        type: number
        required: false
        default: 1
        description: "Seconds to wait after docker-compose initialised"
      no-compose:
        type: boolean
        required: false
        default: false
        description: "Do not run docker-compose even compose file is present"
      os:
        description: "OS version to run the workflow on. If not provided, defaults to 'ubuntu-latest'"
        type: string
        default: ubuntu-latest
        required: false
    secrets:
      ssh-private-key:
        description: "SSH key to use"
        required: false

env:
  GOPRIVATE: ${{ inputs.go-private }}

jobs:
  test:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: "${{ secrets.ssh-private-key }}"
      - run: 'git config --global url."git@github.com:".insteadOf "https://github.com/"'

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true

      - run: 'docker-compose -f "${{ inputs.compose-file }}" up -d --build && sleep ${{ inputs.compose-wait }}'
        if: "${{ !inputs.no-compose && hashFiles(inputs.compose-file) != '' }}"

      - run: make go-test-nocache

      - run: make go-race-nocache
        if: "${{ !inputs.no-race }}"

      - run: 'docker-compose -f "${{ inputs.compose-file }}" down'
        if: "${{ always() && !inputs.no-compose && hashFiles(inputs.compose-file) != '' }}"
