name: Go upload to S3

on:
  workflow_call:
    inputs:
      artifact:
        description: "Artifact file name"
        type: string
        required: false
        default: '${{ github.event.repository.name }}.linux.amd64'
      revision:
        description: "Artifact revision"
        type: string
        required: false
        default: ''
      aws_bucket:
        description: "AWS bucket"
        type: string
        required: false
        default: 'remerge-artifacts-v2'
      directory:
        description: "Directory in AWS bucket"
        type: string
        required: false
        default: '${{ github.repository }}/${{ github.head_ref || github.ref_name }}'
    secrets:
      aws_key_id:
        description: "AWS Key ID"
        required: true
      aws_key_secret:
        description: "AWS Key Secret"
        required: true

jobs:
  go-upload-s3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.artifact }}
    - run: chmod +x ${{ inputs.artifact }}
    - run: tar -czvf ${{ inputs.artifact }}.tar.gz ${{ inputs.artifact }}
      if: "${{ inputs.revision == '' }}"
    - run: echo ${{ inputs.artifact }}-{{ inputs.revision }}.tar.gz
    - run: tar -czvf ${{ inputs.artifact }}-{{ inputs.revision }}.tar.gz ${{ inputs.artifact }}
      if: "${{ inputs.revision != '' }}"
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl private --follow-symlinks --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_key_secret}}
        AWS_S3_BUCKET: ${{ inputs.aws_bucket }}
        SOURCE_DIR: './'
        DEST_DIR: ${{ inputs.directory }}
