name: Handle event that represents a possible dependency update

on:
  workflow_call:
    inputs:
      repo_path:
        type: string
        required: true
        description: "the one that looks like 'github.com/remerge/xyz'"
      repo_name:
        type: string
        required: true
        description: "the one that looks like 'remerge/xyz'"
      os:
        description: "OS version to run the workflow on. If not provided, defaults to 'ubuntu-latest'"
        type: string
        default: ubuntu-latest
        required: false
      sign_commits:
        description: "Sign commits using GPG key, defaults to 'false'"
        type: boolean
        default: false
        required: false
    secrets:
      personal_access_token:
        description: "Need a PAT with update permissions to send events to a repo"
        required: true
      ssh_key:
        description: "Need an SSH key to fetch private repos"
        required: true
      dep_updater_gpg_private_key:
        description: "Need GPG private key for signing commits"
        required: false
      dep_updater_gpg_private_passphrase:
        description: "Need GPG passphrase key for signing commits"
        required: false

env:
  GOPRIVATE: github.com/remerge
  GO111MODULE: on

jobs:
  create-or-update-pull-request:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.ssh_key }}

      - name: Set global git config
        run: git config --global url.git@github.com:.insteadof https://github.com/

      - name: Check out
        uses: actions/checkout@v3

      - run: |
          go get ${{ inputs.repo_path }}
          go mod tidy
          git diff

      - uses: crazy-max/ghaction-import-gpg@v3
        if: ${{ inputs.sign_commits }}
        with:
          gpg-private-key: ${{ secrets.dep_updater_gpg_private_key }}
          passphrase: ${{ secrets.dep_updater_gpg_private_passphrase }}
          git-user-signingkey: true
          git-commit-gpgsign: true

      - name: Create or update pull request to update ${{ inputs.repo_name }}
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.personal_access_token }}
          commit-message: Update ${{ inputs.repo_name }}
          committer: Dependency Updater <tech@remerge.io>
          author: Dependency Updater <tech@remerge.io>
          signoff: false
          branch: update-${{ inputs.repo_name }}
          delete-branch: true
          title: Update ${{ inputs.repo_name }}
          body: |
            `go get ${{ inputs.repo_path }} && go mod tidy`
          labels: depupdater
