---
name: Deploy to Nomad Cluster
on:
  workflow_call:
    inputs:
      cluster_details:
        required: true
        type: string
        description: |
          An json string with details of Nomad clusters to deploy to.
          Available keys and descriptions found below:
          [
            {
              "cluster": Name of the cluster,
              "environment": Application environment to deploy,
              "api_url": Nomad cluster API address,
              "api_key_name": Keyname of the cluster API key set in the secrets
            }
          ]
          Example:
            [
              {
                "cluster": "gce",
                "environment": "production",
                "api_url": "http://nomad.nomad-test.remerge.io/",
                "api_key_name": "gce_nomad_token"
              },
              {
                "cluster": "dw1",
                "environment": "production",
                "api_url": "http://nomad.mon.rmge.net/",
                "api_key_name": "dw1_nomad_token"
              }
            ]
      image_name:
        required: true
        type: string
        description: "Docker image to deploy"
    secrets:
      gce_nomad_token:
        required: false
        description: "Nomad token for accessing Nomad GCE cluster"
      dw1_nomad_token:
        required: false
        description: "Nomad token for accessing Nomad DW1 cluster"

jobs:
  nomad:
    runs-on: [self-hosted, linux]
    strategy:
      matrix:
        cluster_detail: ${{fromJson(inputs.cluster_details)}}
    steps:
      - uses: actions/checkout@v3
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ inputs.image_name }}
          tags: |
            type=sha

      - name: Deploy to Nomad
        if: ${{ github.event_name != 'pull_request' }}
        env:
          NOMAD_TOKEN: ${{ secrets[matrix.cluster_detail.api_key_name] }}
          NOMAD_API: ${{ matrix.cluster_detail.api_url }}
          NOMAD_VAR_task_image: ${{ steps.meta.outputs.tags }}
          NOMAD_VAR_cluster: ${{ matrix.cluster_detail.cluster }}
          NOMAD_VAR_environment: ${{ matrix.cluster_detail.environment }}
        run: |
          nomad run -token="$NOMAD_TOKEN" -address="$NOMAD_API" -detach nomad.hcl
