name: Deploy Application to Nomad Cluster
on:
  workflow_call:
    inputs:
      cluster:
        required: true
        type: string
        description: Nomad Cluster/Datacenter Name
      environment:
        required: true
        type: string
        description: Application environment to deploy
      api_url:
        required: true
        type: string
        description: Nomad cluster API address
      image_name:
        required: true
        type: string
        description: Docker image to deploy to cluster
      run_plan:
        type: boolean
        description: Specify whether to plan nomad job to cluster
        default: true
      run_deploy:
        type: boolean
        description: Specify whether to deploy nomad job to cluster
        default: false
      variables_file_name:
        type: string
        description: Relative path to nomad_pack variable.
        default: ""
      config_file_name:
        type: string
        description: Relative path to nomad_pack variable.
        default: "nomad.hcl"
      notify_github_deployment:
        required: false
        type: boolean
        default: false
        description: Specify whether to create and notify github deployment environments
    secrets:
      nomad_token:
        required: false
        description: "Nomad token for accessing Nomad cluster"
      slack_bot_token:
        required: true
        description: "Access token for Slack"

jobs:
  slack-notify-start:
    if: ${{ github.event_name != 'pull_request' && inputs.run_deploy }}
    uses: remerge/workflows/.github/workflows/slack-notify.yml@main
    with:
      cluster: ${{ inputs.cluster }}
      status: running
    secrets:
      slack_bot_token: ${{ secrets.slack_bot_token }}

  nomad:
    runs-on: [self-hosted, generic, nomad]
    steps:
      - uses: actions/checkout@v3
      - name: command args
        env:
          VAR_FILE: ${{ inputs.variables_file_name }}
        run: |
          if [ -n "$VAR_FILE" ]; then
            echo "NOMAD_ARG=\"-var-file=${VAR_FILE}\"" >> "$GITHUB_ENV"
          fi

      - name: Validate Nomad Configurations
        id: nomad_validate
        env:
          NOMAD_TOKEN: ${{ secrets.nomad_token }}
          NOMAD_ADDR: ${{ inputs.api_url }}
          NOMAD_VAR_task_image: ${{ inputs.image_name }}
          NOMAD_VAR_cluster: ${{ inputs.cluster }}
          NOMAD_VAR_environment: ${{ inputs.environment }}
        run: |
          nomad validate ${{ env.NOMAD_ARG }} ${{ inputs.config_file_name }}

      - name: Run Nomad Plan
        id: nomad_plan
        if: ${{ inputs.run_plan }}
        env:
          NOMAD_TOKEN: ${{ secrets.nomad_token }}
          NOMAD_ADDR: ${{ inputs.api_url }}
          NOMAD_VAR_task_image: ${{ inputs.image_name }}
          NOMAD_VAR_cluster: ${{ inputs.cluster }}
          NOMAD_VAR_environment: ${{ inputs.environment }}
        run: |
          res=$(nomad job plan ${{ env.NOMAD_ARG }} \
           ${{ inputs.config_file_name }}) || ( [ $? -eq 1 ] && true)

          echo "${res}"
          res="${res//'%'/'%25'}"
          res="${res//$'\n'/'%0A'}"
          res="${res//$'\r'/'%0D'}"

          echo "stdout=$res" >> "$GITHUB_OUTPUT"

      - name: PR Comment
        if: ${{ github.event_name == 'pull_request' && inputs.run_plan }}
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.github_token}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Nomad Plan for ${{ inputs.cluster }} \n ${{ steps.nomad_plan.outputs.stdout }}`
            })

      - name: Create github deployment
        if: ${{ github.event_name != 'pull_request' && inputs.run_deploy && inputs.notify_github_deployment }}
        id: deployment
        uses: chrnorm/deployment-action@v2
        with:
          environment: ${{ inputs.environment }}
          token: '${{ github.token }}'

      - name: Deploy to Nomad
        id: nomad_deployment
        if: ${{ github.event_name != 'pull_request' && inputs.run_deploy }}
        env:
          NOMAD_TOKEN: ${{ secrets.nomad_token }}
          NOMAD_ADDR: ${{ inputs.api_url }}
          NOMAD_VAR_task_image: ${{ inputs.image_name }}
          NOMAD_VAR_cluster: ${{ inputs.cluster }}
          NOMAD_VAR_environment: ${{ inputs.environment }}
        run: |
          nomad job run ${{ env.NOMAD_ARG }} -detach ${{ inputs.config_file_name }}

      - name: Update github deployment status
        if: ${{ github.event_name != 'pull_request' && inputs.run_deploy && inputs.notify_github_deployment }}
        uses: chrnorm/deployment-status@v2
        with:
          token: "${{ github.token }}"
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: "${{ steps.nomad_deployment.outcome }}"

  slack-notify-finish:
    if: ${{ always() && needs.nomad.result != 'skipped' && github.event_name != 'pull_request' && inputs.run_deploy }}
    needs: [nomad, slack-notify-start]
    uses: remerge/workflows/.github/workflows/slack-notify.yml@main
    with:
      cluster: ${{ inputs.cluster }}
      status: ${{ needs.nomad.result }}
      update_ts: ${{ needs.slack-notify-start.outputs.ts }}
    secrets:
      slack_bot_token: ${{ secrets.slack_bot_token }}
