name: Notify repos that depend on me

on:
  workflow_call:
    inputs:
      dependants:
        type: string
        required: true
        description: "String containing a JSON list (because we can't pass a list as an input)"
      app_id:
        type: string
        required: true
        description: "App id that we exchange for a token."
    secrets:
      app_key:
        description: "Private app key that we can exchange for a token."
        required: true

jobs:
  notify-all-dependants:
    strategy:
      matrix:
        dependant: ${{ fromJSON(inputs.dependants) }}
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ matrix.dependant }}
      shell: bash

    - name: Use our App Key and App ID to get an App Token
      id: generate_app_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ inputs.app_id }}
        private_key: ${{ secrets.app_key }}

        # Optional (defaults to all the Github App permissions).
        # Using a YAML multiline string to avoid escaping the JSON quotes.
        # permissions: >-
        #   {"members": "read"}

        # Optional (defaults to the current repository).
        # repository: "owner/repo"

    - name: Dispatch Event
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ steps.generate_app_token.outputs.token }}
        repository: remerge/${{ matrix.dependant }}
        event-type: possible-dependency-update
        client-payload: |
          {
            "repo_path": "github.com/${{ github.repository }}",
            "repo_name": "${{ github.repository }}"
          }
