name: Python-based model lint and test

on:
  workflow_call:
    inputs:
      python_version:
        description: "Python version to use. If not provided, will be extracted from pyproject.toml"
        type: string
        required: false
        default: ""
    secrets:
      ssh_key:
        description: |
          SSH key to use to build and test the model. The user of the key must have access to our other private 
          repositories.
        required: true
      fake_google_service_account_json:
        description: |
          Google service account JSON to use while testing. It should be fake credentials, unless your tests are to 
          be run against a real bucket.
        required: true
      pypi_username:
        description: |
          Username to use to log in into our private PyPi server.
        required: true
      pypi_password:
        description: |
          Password to use to log in into our private PyPi server.
        required: true

jobs:
  python-model-lint-and-test:
    runs-on: ubuntu-latest
    name: Python Model Lint & Test
    env:
      GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.fake_google_service_account_json }}
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Extract Python version from pyproject.toml
        run: echo "PYTHON_VERSION=$(grep -E "^python\s?=" < pyproject.toml | awk '{print $3}' | sed -r 's/^"\^?\~?|"$//g')" >> "$GITHUB_ENV"
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ inputs.python_version || env.PYTHON_VERSION }}
          cache: 'poetry'
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: |
            ${{ secrets.ssh_key }}

      - name: Update Git config
        run: |
          git config --global url."git@github.com:".insteadOf "https://github.com/"

      - name: Configure pip to access our private PyPi repo
        run: |
          sudo /bin/bash -c "echo $'[global]\n\
          trusted-host = pypi.remerge.io\n\
                         pypi.org\n\
          \n\
          index-url = https://pypi.org/simple\n\
          extra-index-url = https://${{ secrets.pypi_username }}:${{ secrets.pypi_password }}@pypi.remerge.io/simple'\
          > /etc/pip.conf"
      - name: Configure Poetry to access our private PyPi repo
        run: |
          poetry config repositories.remerge https://pypi.remerge.io
          poetry config http-basic.remerge '${{ secrets.pypi_username }}' '${{ secrets.pypi_password }}'

      - run: poetry install

      - name: Lint
        run: make lint
      - name: Test
        run: |
          make test
